spring:
  datasource:
    url: jdbc:h2:file:./db/h2-demo-db
    #    url: jdbc:h2:mem:h2-demo-db
    driver-class-name: org.h2.Driver
    username: mustard
    password: 206207
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true # Format SQL statements in logs
        use_sql_comments: true # Include SQL comments in logs




